name: weatherbloc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  weather: ^3.1.1
  equatable: ^2.0.5
  geolocator: ^13.0.1
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - .env